package ErrorCode

const (
	NEW_ROOM_UNKOWN             = 200
	NEW_ROOM_SERVER_BUSY        = 201
	NEW_ROOM_NAME_COLLISSION    = 202
	NEW_ROOM_INVALID_NAME       = 203
	NEW_ROOM_INVALID_MAXLOAD    = 204
	NEW_ROOM_INVALID_WELCMSG    = 205
	NEW_ROOM_INVALID_EMPTYCLOSE = 206
	NEW_ROOM_INVALID_PWD        = 207
	NEW_ROOM_TOO_MANY_ROOMS     = 210
	NEW_ROOM_INVALID_CANVAS     = 211
	LOGIN_UNKOWN                = 300
	LOGIN_INVALID_NAME          = 301
	LOGIN_PWD_INCORRECT         = 302
	LOGIN_ROOM_IS_FULL          = 303
	CHECKOUT_UNKNOWN            = 700
	CHECKOUT_KEY_INCORRECT      = 701
	CHECKOUT_TIMEOUT            = 702
)
