package ErrorCode

const (
	LOGIN_UNKOWN           = 300
	LOGIN_INVALID_NAME     = 301
	LOGIN_PWD_INCORRECT    = 302
	LOGIN_ROOM_IS_FULL     = 303
	CHECKOUT_UNKNOWN       = 700
	CHECKOUT_KEY_INCORRECT = 701
	CHECKOUT_TIMEOUT       = 702
)
